image: registry.devops.pku-hit.com/library/ciproto:0.0.1

stages:
  - mvn-deploy

deploy-file-lib:
  stage: mvn-deploy
  script:
  - mkdir -p src/main/java
  - protoc --plugin=protoc-gen-grpc-java=/usr/local/bin/protoc-gen-grpc-java.exe --grpc-java_out=./src/main/java --java_out=./src/main/java  *.proto
  - mvn -DskipTests=true -U clean deploy;
