// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg-response.proto

package libgrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Response) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type GenericResponse struct {
	Resp                 *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Result               *any.Any  `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GenericResponse) Reset()         { *m = GenericResponse{} }
func (m *GenericResponse) String() string { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()    {}
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{1}
}

func (m *GenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericResponse.Unmarshal(m, b)
}
func (m *GenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericResponse.Marshal(b, m, deterministic)
}
func (m *GenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericResponse.Merge(m, src)
}
func (m *GenericResponse) XXX_Size() int {
	return xxx_messageInfo_GenericResponse.Size(m)
}
func (m *GenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericResponse proto.InternalMessageInfo

func (m *GenericResponse) GetResp() *Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *GenericResponse) GetResult() *any.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "libgrpc.Response")
	proto.RegisterType((*GenericResponse)(nil), "libgrpc.GenericResponse")
}

func init() { proto.RegisterFile("msg-response.proto", fileDescriptor_2356d04dff83e48a) }

var fileDescriptor_2356d04dff83e48a = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0xc1, 0x8e, 0x82, 0x30,
	0x14, 0x45, 0xc3, 0x84, 0x61, 0xc6, 0xba, 0x30, 0x36, 0x2e, 0x2a, 0x2b, 0x43, 0x62, 0xe2, 0x42,
	0x1f, 0x09, 0x7e, 0x81, 0x6e, 0xdc, 0xf7, 0x0f, 0xa4, 0xbc, 0x36, 0x24, 0xd0, 0x47, 0x5a, 0x58,
	0xf0, 0xf7, 0x86, 0x02, 0xee, 0x5e, 0x6e, 0xcf, 0xe9, 0xbd, 0x8c, 0xb7, 0xde, 0xdc, 0x1c, 0xfa,
	0x8e, 0xac, 0x47, 0xe8, 0x1c, 0xf5, 0xc4, 0xff, 0x9a, 0xba, 0x34, 0xae, 0x53, 0xe9, 0xd1, 0x10,
	0x99, 0x06, 0xf3, 0x10, 0x97, 0x83, 0xce, 0xdf, 0x76, 0x9c, 0x99, 0xac, 0x60, 0xff, 0x72, 0xb1,
	0x38, 0x67, 0xb1, 0xa2, 0x0a, 0x45, 0x74, 0x8a, 0x2e, 0x1b, 0x19, 0xee, 0x29, 0xab, 0xad, 0x26,
	0xf1, 0x33, 0x67, 0xd3, 0x9d, 0x69, 0xb6, 0x7b, 0xa1, 0x45, 0x57, 0xab, 0xaf, 0x7a, 0x66, 0xf1,
	0x54, 0x1e, 0xd4, 0x6d, 0xb1, 0x87, 0xa5, 0x19, 0x56, 0x40, 0x86, 0x67, 0x7e, 0x65, 0x89, 0x43,
	0x3f, 0x34, 0xbd, 0xf8, 0x0d, 0xe0, 0x01, 0xe6, 0x65, 0xb0, 0x2e, 0x83, 0x87, 0x1d, 0xe5, 0xc2,
	0x3c, 0x53, 0x26, 0x14, 0xb5, 0xa0, 0x69, 0xb0, 0x15, 0x3a, 0x50, 0xe4, 0x70, 0xfd, 0xb8, 0x4c,
	0x82, 0x71, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x25, 0x65, 0xc1, 0x76, 0xf8, 0x00, 0x00, 0x00,
}
