// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg-response.proto

package libgrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Response) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type BoolResponse struct {
	Resp                 *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Result               bool      `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BoolResponse) Reset()         { *m = BoolResponse{} }
func (m *BoolResponse) String() string { return proto.CompactTextString(m) }
func (*BoolResponse) ProtoMessage()    {}
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{1}
}

func (m *BoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolResponse.Unmarshal(m, b)
}
func (m *BoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolResponse.Marshal(b, m, deterministic)
}
func (m *BoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolResponse.Merge(m, src)
}
func (m *BoolResponse) XXX_Size() int {
	return xxx_messageInfo_BoolResponse.Size(m)
}
func (m *BoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BoolResponse proto.InternalMessageInfo

func (m *BoolResponse) GetResp() *Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *BoolResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type IntResponse struct {
	Resp                 *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Result               int32     `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *IntResponse) Reset()         { *m = IntResponse{} }
func (m *IntResponse) String() string { return proto.CompactTextString(m) }
func (*IntResponse) ProtoMessage()    {}
func (*IntResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{2}
}

func (m *IntResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntResponse.Unmarshal(m, b)
}
func (m *IntResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntResponse.Marshal(b, m, deterministic)
}
func (m *IntResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntResponse.Merge(m, src)
}
func (m *IntResponse) XXX_Size() int {
	return xxx_messageInfo_IntResponse.Size(m)
}
func (m *IntResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IntResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IntResponse proto.InternalMessageInfo

func (m *IntResponse) GetResp() *Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *IntResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type StringResponse struct {
	Resp                 *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Result               string    `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StringResponse) Reset()         { *m = StringResponse{} }
func (m *StringResponse) String() string { return proto.CompactTextString(m) }
func (*StringResponse) ProtoMessage()    {}
func (*StringResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{3}
}

func (m *StringResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringResponse.Unmarshal(m, b)
}
func (m *StringResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringResponse.Marshal(b, m, deterministic)
}
func (m *StringResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringResponse.Merge(m, src)
}
func (m *StringResponse) XXX_Size() int {
	return xxx_messageInfo_StringResponse.Size(m)
}
func (m *StringResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StringResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StringResponse proto.InternalMessageInfo

func (m *StringResponse) GetResp() *Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *StringResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type BytesResponse struct {
	Resp                 *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Result               []byte    `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BytesResponse) Reset()         { *m = BytesResponse{} }
func (m *BytesResponse) String() string { return proto.CompactTextString(m) }
func (*BytesResponse) ProtoMessage()    {}
func (*BytesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{4}
}

func (m *BytesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesResponse.Unmarshal(m, b)
}
func (m *BytesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesResponse.Marshal(b, m, deterministic)
}
func (m *BytesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesResponse.Merge(m, src)
}
func (m *BytesResponse) XXX_Size() int {
	return xxx_messageInfo_BytesResponse.Size(m)
}
func (m *BytesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BytesResponse proto.InternalMessageInfo

func (m *BytesResponse) GetResp() *Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *BytesResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type MapResponse struct {
	Resp                 *Response         `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Result               map[string]string `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MapResponse) Reset()         { *m = MapResponse{} }
func (m *MapResponse) String() string { return proto.CompactTextString(m) }
func (*MapResponse) ProtoMessage()    {}
func (*MapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{5}
}

func (m *MapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapResponse.Unmarshal(m, b)
}
func (m *MapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapResponse.Marshal(b, m, deterministic)
}
func (m *MapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapResponse.Merge(m, src)
}
func (m *MapResponse) XXX_Size() int {
	return xxx_messageInfo_MapResponse.Size(m)
}
func (m *MapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MapResponse proto.InternalMessageInfo

func (m *MapResponse) GetResp() *Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *MapResponse) GetResult() map[string]string {
	if m != nil {
		return m.Result
	}
	return nil
}

type PageInfo struct {
	Current              int32    `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{6}
}

func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (m *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(m, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetCurrent() int32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *PageInfo) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PageInfo) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type PageResponse struct {
	Resp                 *Response  `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	IsEnd                bool       `protobuf:"varint,2,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	PageInfo             *PageInfo  `protobuf:"bytes,3,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	Result               []*any.Any `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PageResponse) Reset()         { *m = PageResponse{} }
func (m *PageResponse) String() string { return proto.CompactTextString(m) }
func (*PageResponse) ProtoMessage()    {}
func (*PageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{7}
}

func (m *PageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageResponse.Unmarshal(m, b)
}
func (m *PageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageResponse.Marshal(b, m, deterministic)
}
func (m *PageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageResponse.Merge(m, src)
}
func (m *PageResponse) XXX_Size() int {
	return xxx_messageInfo_PageResponse.Size(m)
}
func (m *PageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PageResponse proto.InternalMessageInfo

func (m *PageResponse) GetResp() *Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *PageResponse) GetIsEnd() bool {
	if m != nil {
		return m.IsEnd
	}
	return false
}

func (m *PageResponse) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

func (m *PageResponse) GetResult() []*any.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

type GenericResponse struct {
	Resp                 *Response `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Result               *any.Any  `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GenericResponse) Reset()         { *m = GenericResponse{} }
func (m *GenericResponse) String() string { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()    {}
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{8}
}

func (m *GenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericResponse.Unmarshal(m, b)
}
func (m *GenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericResponse.Marshal(b, m, deterministic)
}
func (m *GenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericResponse.Merge(m, src)
}
func (m *GenericResponse) XXX_Size() int {
	return xxx_messageInfo_GenericResponse.Size(m)
}
func (m *GenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericResponse proto.InternalMessageInfo

func (m *GenericResponse) GetResp() *Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *GenericResponse) GetResult() *any.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "libgrpc.Response")
	proto.RegisterType((*BoolResponse)(nil), "libgrpc.BoolResponse")
	proto.RegisterType((*IntResponse)(nil), "libgrpc.IntResponse")
	proto.RegisterType((*StringResponse)(nil), "libgrpc.StringResponse")
	proto.RegisterType((*BytesResponse)(nil), "libgrpc.BytesResponse")
	proto.RegisterType((*MapResponse)(nil), "libgrpc.MapResponse")
	proto.RegisterMapType((map[string]string)(nil), "libgrpc.MapResponse.ResultEntry")
	proto.RegisterType((*PageInfo)(nil), "libgrpc.PageInfo")
	proto.RegisterType((*PageResponse)(nil), "libgrpc.PageResponse")
	proto.RegisterType((*GenericResponse)(nil), "libgrpc.GenericResponse")
}

func init() { proto.RegisterFile("msg-response.proto", fileDescriptor_2356d04dff83e48a) }

var fileDescriptor_2356d04dff83e48a = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x5f, 0xcb, 0xda, 0x30,
	0x14, 0xc6, 0xa9, 0x5a, 0xad, 0xa7, 0xee, 0x5f, 0x90, 0xd1, 0xf5, 0x4a, 0x0a, 0x03, 0x2f, 0x34,
	0x82, 0xbb, 0x71, 0xbb, 0x9b, 0x20, 0x43, 0x98, 0xdb, 0xa8, 0xb0, 0xfb, 0x5a, 0x4f, 0x4b, 0x59,
	0x4d, 0x4a, 0x9a, 0x0e, 0xba, 0x4f, 0xb4, 0x7d, 0xcb, 0x91, 0xb4, 0x0d, 0x7d, 0xaf, 0x5e, 0xc4,
	0xbb, 0x3c, 0xa7, 0xe7, 0xf9, 0x3d, 0xe9, 0x49, 0x02, 0xe4, 0x56, 0xa6, 0x6b, 0x81, 0x65, 0xc1,
	0x59, 0x89, 0xb4, 0x10, 0x5c, 0x72, 0x32, 0xc9, 0xb3, 0x4b, 0x2a, 0x8a, 0xd8, 0x7f, 0x97, 0x72,
	0x9e, 0xe6, 0xb8, 0xd1, 0xe5, 0x4b, 0x95, 0x6c, 0x22, 0x56, 0x37, 0x3d, 0xc1, 0x16, 0x9c, 0xb0,
	0x75, 0x11, 0x02, 0xa3, 0x98, 0x5f, 0xd1, 0xb3, 0x16, 0xd6, 0x72, 0x1a, 0xea, 0xb5, 0xaa, 0x65,
	0x2c, 0xe1, 0xde, 0xa0, 0xa9, 0xa9, 0x75, 0x70, 0x82, 0xd9, 0x9e, 0xf3, 0xdc, 0xf8, 0xde, 0xc3,
	0x48, 0x25, 0x6b, 0x9f, 0xbb, 0x7d, 0x43, 0xdb, 0x58, 0xda, 0x35, 0x84, 0xfa, 0x33, 0x79, 0x0b,
	0x63, 0x81, 0x65, 0x95, 0x4b, 0x0d, 0x73, 0xc2, 0x56, 0x05, 0x5f, 0xc1, 0x3d, 0x32, 0xf9, 0x18,
	0xcd, 0x36, 0xb4, 0xef, 0xf0, 0xf2, 0x2c, 0x45, 0xc6, 0xd2, 0xc7, 0x80, 0x53, 0x03, 0xfc, 0x06,
	0x2f, 0xf6, 0xb5, 0xc4, 0xf2, 0x31, 0xde, 0xcc, 0xf0, 0xfe, 0x59, 0xe0, 0x9e, 0xa2, 0xe2, 0x5e,
	0xdc, 0xae, 0x87, 0x1b, 0x2e, 0xdd, 0xed, 0xc2, 0x34, 0xf6, 0x60, 0xca, 0x54, 0xe5, 0xf2, 0xc0,
	0xa4, 0xa8, 0xbb, 0x40, 0xff, 0x23, 0xb8, 0xbd, 0x32, 0x79, 0x0d, 0xc3, 0x5f, 0x58, 0xb7, 0x87,
	0xac, 0x96, 0x64, 0x0e, 0xf6, 0xef, 0x28, 0xaf, 0xb0, 0xfd, 0xf1, 0x46, 0x7c, 0x1a, 0xec, 0xac,
	0xe0, 0x27, 0x38, 0x3f, 0xa2, 0x14, 0x8f, 0x2c, 0xe1, 0xc4, 0x83, 0x49, 0x5c, 0x09, 0x81, 0x4c,
	0x6a, 0xaf, 0x1d, 0x76, 0x52, 0xf9, 0x25, 0x97, 0x51, 0xde, 0x9e, 0x44, 0x23, 0x88, 0x0f, 0x4e,
	0x11, 0xa5, 0x78, 0xce, 0xfe, 0xa0, 0x37, 0xd4, 0x1f, 0x8c, 0x0e, 0xfe, 0x5a, 0x30, 0x53, 0xe0,
	0x7b, 0x87, 0x30, 0x07, 0x3b, 0x2b, 0x0f, 0xec, 0xda, 0xde, 0xa0, 0x46, 0x90, 0x75, 0x93, 0xa4,
	0x76, 0xa9, 0x93, 0xfa, 0x80, 0x6e, 0xfb, 0xa1, 0x69, 0x21, 0x2b, 0x33, 0xc9, 0x91, 0x9e, 0xe4,
	0x9c, 0x36, 0xcf, 0x83, 0x76, 0xcf, 0x83, 0x7e, 0x66, 0x66, 0x7a, 0x41, 0x02, 0xaf, 0xbe, 0x20,
	0x43, 0x91, 0xc5, 0xf7, 0x6e, 0x76, 0xf5, 0xe4, 0x02, 0x3c, 0x93, 0xb3, 0xf7, 0xc1, 0x8b, 0xf9,
	0x8d, 0x26, 0xbc, 0x62, 0x57, 0x14, 0x34, 0xe6, 0x02, 0x3b, 0xf0, 0x65, 0xac, 0x1d, 0x1f, 0xfe,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x6e, 0xdd, 0x6b, 0xe5, 0x03, 0x00, 0x00,
}
